select AUDITORIUM.AUDITORIUM[Код аудитории], AUDITORIUM_TYPE.AUDITORIUM_TYPENAME[Имя типа с компьютером]
from AUDITORIUM inner join AUDITORIUM_TYPE
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%'