select distinct PULPIT.PULPIT_NAME[Кафедры с факультета с профессией с технологиями]		--, FACULTY.FACULTY, PROFESSION.PROFESSION_NAME
from PULPIT, FACULTY, PROFESSION
where FACULTY.FACULTY = PULPIT.FACULTY
and FACULTY.FACULTY in (select PROFESSION.FACULTY from PROFESSION where (PROFESSION_NAME like '%технологи%'));